BEGIN;

ALTER TABLE signatures
    ADD COLUMN ClaTextUrl VARCHAR(250) NOT NULL DEFAULT '',
    ADD COLUMN ClaText TEXT NOT NULL DEFAULT '';

ALTER TABLE signatures
    ALTER COLUMN ClaTextUrl DROP DEFAULT,
    ALTER COLUMN ClaText DROP DEFAULT;

COMMIT;
